xrdb -merge ~/.config/X11/xresources
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
        export $(dbus-launch)
fi
sudo surface-dtx-daemon &
pipewire &
wireplumber &
pipewire-pulse &
/usr/libexec/xfce-polkit &

feh --no-fehbg --bg-fill ~/.config/xmonad/wallpapers/aria.png
stalonetray -c ~/.config/stalonetray/stalonetrayrc &
nm-applet &
fcitx -d &
xcompmgr &

exec xmonad
