#!/bin/sh

src="$(readlink -e xmonad.hs)"
obj="$XDG_CACHE_HOME/xmonad"
mkdir -p "$obj"

exec stack ghc -- --make "$src" -o "$1" \
     -i -ilib -fforce-recomp -main-is main -v0 \
     -odir "$obj" -hidir "$obj"
