require('impatient')
require('packer_init')
require('core/options')
require('core/autocmds')
require('core/keymaps')
require('core/colors')
require('plugins/nvim-treesitter')
require('plugins/vimtex')
require('plugins/nvim-lspconfig')
require('plugins/cmp')
require('plugins/lualine')
require('plugins/filetype-nvim')
require('plugins/hydra')
--[[ require('plugins/dap')
require('plugins/dapui') ]]
require('plugins/misc')
